export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

export const MY_ORDER_LIST_REQUEST = 'MY_ORDER_LIST_REQUEST'
export const MY_ORDER_LIST_SUCCESS = 'MY_ORDER_LIST_SUCCESS'
export const MY_ORDER_LIST_FAIL = 'MY_ORDER_LIST_FAIL'

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL'

export const UPDATE_ORDER_DELIVERED_REQUEST = 'UPDATE_ORDER_DELIVERED_REQUEST'
export const UPDATE_ORDER_DELIVERED_SUCCESS = 'UPDATE_ORDER_DELIVERED_SUCCESS'
export const UPDATE_ORDER_DELIVERED_FAIL = 'UPDATE_ORDER_DELIVERED_FAIL'
export const UPDATE_ORDER_DELIVERED_RESET = 'UPDATE_ORDER_DELIVERED_RESET'
